name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate data
        run: python -m src.data.make_dataset --n-samples 5000 --fraud-rate 0.02
      - name: Build features
        run: python -m src.features.build_features
      - name: Run tests
        run: pytest -q